package src;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dongbo
 */
public class DailyChangeFrame extends javax.swing.JFrame {
    
    Socket socket;
    String str1 ="";
    DataOutputStream out;
    BufferedReader in; 
    
    //parse the server
    static String dailychange_serverinput;
    static String[] dailychange_seg;
    static ArrayList<String []> dailychange_list = new ArrayList<String []>();
    
    /**
     * Creates new form MainFrame
     */
    public DailyChangeFrame(Socket socket) throws IOException {
    this.socket = socket; 
    out= new DataOutputStream(socket.getOutputStream());
    in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
    out.write("get_change()".getBytes());
 
    for (int i = 0; i<27; i++){
        str1 += in.readLine() +"\n";
        
    }
       //str1 = "FM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM GX CB SM\nFM\nCB\nSM\n";
        
        dailychange_serverinput = str1;
        
        dailychange_seg = dailychange_serverinput.split("\n");
        for (int i = 0; i<dailychange_seg.length; i++){
            dailychange_seg[i] = dailychange_seg[i].trim();
        }
        System.out.println(dailychange_seg[0]);
        for (int i = 0; i<dailychange_seg.length; i++){
            dailychange_list.add(dailychange_seg[i].split(" "));
            //System.out.println(dailychange_vector.get(i));
        }
        
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        space_1 = new javax.swing.JTextField();
        closing_book_header = new javax.swing.JTextField();
        change_header = new javax.swing.JTextField();
        ticker_header = new javax.swing.JTextField();
        opening_book_amount_header = new javax.swing.JTextField();
        opening_book_risk_header = new javax.swing.JTextField();
        opening_book_LGD_header = new javax.swing.JTextField();
        opening_book_header = new javax.swing.JTextField();
        closing_book_amount_header = new javax.swing.JTextField();
        closing_book_risk_header = new javax.swing.JTextField();
        closing_book_LGD_header = new javax.swing.JTextField();
        change_amount_header = new javax.swing.JTextField();
        change_risk_header = new javax.swing.JTextField();
        change_LGD_header = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticker_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ticker_ob_amount_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ticker_ob_risk_list = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        ticker_ob_LGD_list = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        ticker_cb_amount_list = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        ticker_cb_risk_list = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        ticker_cb_LGD_list = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        ticker_change_amount_list = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        ticker_change_risk_list = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        ticker_change_LGD_list = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        quality_list = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        quality_ob_amount_list = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        quality_ob_risk_list = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        quality_ob_LGD_list = new javax.swing.JList<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        quality_cb_amount_list = new javax.swing.JList<>();
        jScrollPane17 = new javax.swing.JScrollPane();
        quality_cb_risk_list = new javax.swing.JList<>();
        jScrollPane18 = new javax.swing.JScrollPane();
        quality_cb_LGD_list = new javax.swing.JList<>();
        jScrollPane19 = new javax.swing.JScrollPane();
        quality_change_amont_listy = new javax.swing.JList<>();
        jScrollPane20 = new javax.swing.JScrollPane();
        quality_change_risk_list = new javax.swing.JList<>();
        jScrollPane21 = new javax.swing.JScrollPane();
        quality_change_LGD_list = new javax.swing.JList<>();
        jScrollPane22 = new javax.swing.JScrollPane();
        var_ob_list = new javax.swing.JList<>();
        jScrollPane23 = new javax.swing.JScrollPane();
        var_cb_list = new javax.swing.JList<>();
        jScrollPane24 = new javax.swing.JScrollPane();
        var_list = new javax.swing.JList<>();
        jScrollPane25 = new javax.swing.JScrollPane();
        var_change_list = new javax.swing.JList<>();
        execution_time_header = new javax.swing.JTextField();
        user_time_header = new javax.swing.JTextField();
        real_time_header = new javax.swing.JTextField();
        sever_sider_header = new javax.swing.JTextField();
        system_time_header = new javax.swing.JTextField();
        jScrollPane26 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane27 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane28 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        space_1.setEditable(false);
        space_1.setBackground(new java.awt.Color(204, 204, 255));
        space_1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        space_1.setText("Categories");
        space_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space_1ActionPerformed(evt);
            }
        });

        closing_book_header.setEditable(false);
        closing_book_header.setBackground(new java.awt.Color(255, 255, 153));
        closing_book_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        closing_book_header.setText("Closing Book");

        change_header.setEditable(false);
        change_header.setBackground(new java.awt.Color(204, 255, 255));
        change_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        change_header.setText("Change");

        ticker_header.setEditable(false);
        ticker_header.setBackground(new java.awt.Color(204, 204, 255));
        ticker_header.setText("Ticker");

        opening_book_amount_header.setEditable(false);
        opening_book_amount_header.setText("Amount");

        opening_book_risk_header.setEditable(false);
        opening_book_risk_header.setText("Risk");
        opening_book_risk_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opening_book_risk_headerActionPerformed(evt);
            }
        });

        opening_book_LGD_header.setEditable(false);
        opening_book_LGD_header.setText("LGD");

        opening_book_header.setEditable(false);
        opening_book_header.setBackground(new java.awt.Color(255, 204, 153));
        opening_book_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        opening_book_header.setText("Opening Book");

        closing_book_amount_header.setEditable(false);
        closing_book_amount_header.setText("Amount");

        closing_book_risk_header.setEditable(false);
        closing_book_risk_header.setText("Risk");

        closing_book_LGD_header.setEditable(false);
        closing_book_LGD_header.setText("LGD");
        closing_book_LGD_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closing_book_LGD_headerActionPerformed(evt);
            }
        });

        change_amount_header.setEditable(false);
        change_amount_header.setText("Amount");

        change_risk_header.setEditable(false);
        change_risk_header.setText("Risk");

        change_LGD_header.setEditable(false);
        change_LGD_header.setText("LGD");
        change_LGD_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_LGD_headerActionPerformed(evt);
            }
        });

        ticker_list.setBackground(new java.awt.Color(204, 204, 255));
        ticker_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = dailychange_list.get(0);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ticker_list.setVisibleRowCount(14);
        jScrollPane2.setViewportView(ticker_list);

        ticker_ob_amount_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(1);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ticker_ob_amount_list);

        ticker_ob_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(2);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(ticker_ob_risk_list);

        ticker_ob_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(3);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(ticker_ob_LGD_list);

        ticker_cb_amount_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(4);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(ticker_cb_amount_list);

        ticker_cb_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(5);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(ticker_cb_risk_list);

        ticker_cb_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(6);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(ticker_cb_LGD_list);

        ticker_change_amount_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(7);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(ticker_change_amount_list);

        ticker_change_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(8);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(ticker_change_risk_list);

        ticker_change_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(9);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(ticker_change_LGD_list);

        quality_list.setBackground(new java.awt.Color(204, 204, 255));
        quality_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(10);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(quality_list);

        quality_ob_amount_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(11);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(quality_ob_amount_list);

        quality_ob_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(12);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(quality_ob_risk_list);

        quality_ob_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(13);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(quality_ob_LGD_list);

        quality_cb_amount_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(14);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(quality_cb_amount_list);

        quality_cb_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(15);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane17.setViewportView(quality_cb_risk_list);

        quality_cb_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(16);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane18.setViewportView(quality_cb_LGD_list);

        quality_change_amont_listy.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(17);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane19.setViewportView(quality_change_amont_listy);

        quality_change_risk_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(18);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane20.setViewportView(quality_change_risk_list);

        quality_change_LGD_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(19);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane21.setViewportView(quality_change_LGD_list);

        var_ob_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(21);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane22.setViewportView(var_ob_list);

        var_cb_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(22);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane23.setViewportView(var_cb_list);

        var_list.setBackground(new java.awt.Color(204, 204, 255));
        var_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(20);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane24.setViewportView(var_list);

        var_change_list.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(23);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane25.setViewportView(var_change_list);

        execution_time_header.setEditable(false);
        execution_time_header.setForeground(new java.awt.Color(255, 51, 51));
        execution_time_header.setText(" execution time:");

        user_time_header.setEditable(false);
        user_time_header.setForeground(new java.awt.Color(255, 51, 51));
        user_time_header.setText("user time");
        user_time_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_time_headerActionPerformed(evt);
            }
        });

        real_time_header.setEditable(false);
        real_time_header.setForeground(new java.awt.Color(255, 51, 51));
        real_time_header.setText("real time");

        sever_sider_header.setEditable(false);
        sever_sider_header.setForeground(new java.awt.Color(255, 51, 51));
        sever_sider_header.setText("(server side)");

        system_time_header.setEditable(false);
        system_time_header.setForeground(new java.awt.Color(255, 51, 51));
        system_time_header.setText("system");

        jList1.setForeground(new java.awt.Color(255, 51, 51));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(24);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane26.setViewportView(jList1);

        jList2.setForeground(new java.awt.Color(255, 51, 51));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(25);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane27.setViewportView(jList2);

        jList3.setForeground(new java.awt.Color(255, 51, 51));
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            //String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            String[] strings = dailychange_list.get(26);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane28.setViewportView(jList3);

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel1.setText("                                                   Daily Change by Issuer (amounts in 000's)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(execution_time_header)
                            .addComponent(sever_sider_header))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(real_time_header, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user_time_header, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(system_time_header, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ticker_header, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(space_1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(opening_book_amount_header, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(opening_book_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opening_book_header, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opening_book_LGD_header, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(closing_book_amount_header, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(closing_book_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(closing_book_LGD_header, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(closing_book_header, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(change_header)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(change_amount_header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(change_risk_header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(change_LGD_header, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closing_book_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opening_book_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticker_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opening_book_amount_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opening_book_LGD_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closing_book_amount_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closing_book_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closing_book_LGD_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_amount_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_LGD_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opening_book_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane12)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(execution_time_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(real_time_header, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_time_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(system_time_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sever_sider_header)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opening_book_risk_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opening_book_risk_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opening_book_risk_headerActionPerformed

    private void space_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_space_1ActionPerformed

    private void change_LGD_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_LGD_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change_LGD_headerActionPerformed

    private void closing_book_LGD_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closing_book_LGD_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closing_book_LGD_headerActionPerformed

    private void user_time_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_time_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_time_headerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyChangeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyChangeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyChangeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyChangeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //input1 = "GM FX SB";
        //list1 = input1.split(" ");
        // int size1 = list1.length;//what feihong write
        
        //dailychange_serverinput = "GM FX\n12 13";
        
        
        
        
        //read the serverinput
        
        
        
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DailyChangeFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField change_LGD_header;
    private javax.swing.JTextField change_amount_header;
    private javax.swing.JTextField change_header;
    private javax.swing.JTextField change_risk_header;
    private javax.swing.JTextField closing_book_LGD_header;
    private javax.swing.JTextField closing_book_amount_header;
    private javax.swing.JTextField closing_book_header;
    private javax.swing.JTextField closing_book_risk_header;
    private javax.swing.JTextField execution_time_header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField opening_book_LGD_header;
    private javax.swing.JTextField opening_book_amount_header;
    private javax.swing.JTextField opening_book_header;
    private javax.swing.JTextField opening_book_risk_header;
    private javax.swing.JList<String> quality_cb_LGD_list;
    private javax.swing.JList<String> quality_cb_amount_list;
    private javax.swing.JList<String> quality_cb_risk_list;
    private javax.swing.JList<String> quality_change_LGD_list;
    private javax.swing.JList<String> quality_change_amont_listy;
    private javax.swing.JList<String> quality_change_risk_list;
    private javax.swing.JList<String> quality_list;
    private javax.swing.JList<String> quality_ob_LGD_list;
    private javax.swing.JList<String> quality_ob_amount_list;
    private javax.swing.JList<String> quality_ob_risk_list;
    private javax.swing.JTextField real_time_header;
    private javax.swing.JTextField sever_sider_header;
    private javax.swing.JTextField space_1;
    private javax.swing.JTextField system_time_header;
    private javax.swing.JList<String> ticker_cb_LGD_list;
    private javax.swing.JList<String> ticker_cb_amount_list;
    private javax.swing.JList<String> ticker_cb_risk_list;
    private javax.swing.JList<String> ticker_change_LGD_list;
    private javax.swing.JList<String> ticker_change_amount_list;
    private javax.swing.JList<String> ticker_change_risk_list;
    private javax.swing.JTextField ticker_header;
    private javax.swing.JList<String> ticker_list;
    private javax.swing.JList<String> ticker_ob_LGD_list;
    private javax.swing.JList<String> ticker_ob_amount_list;
    private javax.swing.JList<String> ticker_ob_risk_list;
    private javax.swing.JTextField user_time_header;
    private javax.swing.JList<String> var_cb_list;
    private javax.swing.JList<String> var_change_list;
    private javax.swing.JList<String> var_list;
    private javax.swing.JList<String> var_ob_list;
    // End of variables declaration//GEN-END:variables
}
