/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import static src.DailyChangeFrame.dailychange_serverinput;

/**
 *
 * @author apple
 */
public class RiskByMaturityFrame extends javax.swing.JFrame {

    /**
     * Creates new form RiskByMaturityFrame
     */
    Socket socket;
    String str2 ;
     String spread1 = "0";
     String spread2 = "0";
     String spread3 = "0";
     String spread4 = "0";
    DataOutputStream out;
    BufferedReader in;
     double count = 1;
     double rate ;
    int num;
    
    //parse the server
    static String riskbymaturity_serverinput;
    static String[] riskbymaturity_seg;
    //static ArrayList<String []> dailychange_list = new ArrayList<String []>();
    
    
     public RiskByMaturityFrame(Socket socket,String str1,String str2, String str3,String str4, double count,double rate,int num) throws IOException {
     this.spread1 = str1;
     this.spread2 = str2;
     this.spread3 = str3;
     this.spread4 = str4;
     this.rate = rate;
     this.count = count;
     this.socket = socket;
     this.num = num;
     out= new DataOutputStream(socket.getOutputStream());
        in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        this.socket = socket; 
        if(num == 1){
        String arg0 = "get_risk("+spread1+","+spread2+","+spread3+","+spread4+")";
         out.write(arg0.getBytes());
        }else if(num == 2){
        String arg0 ="get_risk_with_shift("+rate+spread1+","+spread2+","+spread3+","+spread4+")";
         out.write(arg0.getBytes());
        }
       
        str2 = in.readLine();
        System.out.println(str2);
      
       //str2 ="1 2 3 4 5 6 7 8 9 10 11 12";
        riskbymaturity_serverinput = str2;
        riskbymaturity_seg = riskbymaturity_serverinput.split(" ");
         initComponents(); 
     }
    
    public RiskByMaturityFrame(Socket socket) throws IOException {
       out= new DataOutputStream(socket.getOutputStream());
        in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        this.socket = socket; 
        String arg0 = "get_risk("+spread1+","+spread2+","+spread3+","+spread4+")";
        out.write(arg0.getBytes());
        str2 = in.readLine();
        System.out.println(str2);
       
       //str2 ="1 2 3 4 5 6 7 8 9 10 11 12";
        riskbymaturity_serverinput = str2;
        riskbymaturity_seg = riskbymaturity_serverinput.split(" ");
         initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_header = new javax.swing.JTextField();
        twoyear_header = new javax.swing.JTextField();
        fiveyear_header = new javax.swing.JTextField();
        tenyear_header = new javax.swing.JTextField();
        thirtyear_header = new javax.swing.JTextField();
        twoyear_risk_header = new javax.swing.JTextField();
        twoyear_mv_header = new javax.swing.JTextField();
        fiveyear_mv_header = new javax.swing.JTextField();
        tenyear_mv_header = new javax.swing.JTextField();
        thirtyear_mv_header = new javax.swing.JTextField();
        fiveyear_risk_header = new javax.swing.JTextField();
        tenyear_risk_header = new javax.swing.JTextField();
        thirtyear_risk_header = new javax.swing.JTextField();
        closing_file_header = new javax.swing.JTextField();
        twoyear_closing_file_risk = new javax.swing.JTextField();
        twoyear_closing_file_mv = new javax.swing.JTextField();
        fiveyear_closing_file_risk = new javax.swing.JTextField();
        fiveyear_closing_file_mv = new javax.swing.JTextField();
        tenyear_closing_file_risk = new javax.swing.JTextField();
        tenyear_closing_file_mv = new javax.swing.JTextField();
        thirtyear_closing_file_risk = new javax.swing.JTextField();
        thirtyear_closing_file_mv = new javax.swing.JTextField();
        twoyear_hedge_header = new javax.swing.JTextField();
        twoyear_hedge_mv = new javax.swing.JTextField();
        fiveyear_hedge_mv = new javax.swing.JTextField();
        tenyear_hedge_mv = new javax.swing.JTextField();
        thirtyear_hedge_mv = new javax.swing.JTextField();
        yield_curve_header = new javax.swing.JTextField();
        twoyear_yield_curve_mv = new javax.swing.JTextField();
        fiveyear_yield_curve_mv = new javax.swing.JTextField();
        tenyear_yield_curve_mv = new javax.swing.JTextField();
        thirtyear_yield_curve_mv = new javax.swing.JTextField();
        button_up = new javax.swing.JButton();
        button_down = new javax.swing.JButton();
        button_original = new javax.swing.JButton();
        spread_header = new javax.swing.JTextField();
        twoyear_spread_mv = new javax.swing.JTextField();
        fiveyear_spread_mv = new javax.swing.JTextField();
        tenyear_spread_mv = new javax.swing.JTextField();
        thirtyear_spread_mv = new javax.swing.JTextField();
        execution_time_header2 = new javax.swing.JTextField();
        real_time_header2 = new javax.swing.JTextField();
        user_time_header2 = new javax.swing.JTextField();
        system_time_header2 = new javax.swing.JTextField();
        sever_side_header2 = new javax.swing.JTextField();
        real_time2 = new javax.swing.JTextField();
        user_time2 = new javax.swing.JTextField();
        system_time2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        book_header.setEditable(false);
        book_header.setBackground(new java.awt.Color(204, 204, 255));
        book_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        book_header.setText("book");

        twoyear_header.setBackground(new java.awt.Color(255, 204, 153));
        twoyear_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        twoyear_header.setText("2YR");

        fiveyear_header.setEditable(false);
        fiveyear_header.setBackground(new java.awt.Color(255, 255, 153));
        fiveyear_header.setText("5YR");

        tenyear_header.setEditable(false);
        tenyear_header.setBackground(new java.awt.Color(204, 255, 255));
        tenyear_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tenyear_header.setText("10YR");

        thirtyear_header.setEditable(false);
        thirtyear_header.setBackground(new java.awt.Color(204, 255, 204));
        thirtyear_header.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        thirtyear_header.setText("30YR");

        twoyear_risk_header.setText("Risk");

        twoyear_mv_header.setText("Mkt Value");

        fiveyear_mv_header.setText("Mkt Value");

        tenyear_mv_header.setText("Mkt Value");
        tenyear_mv_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenyear_mv_headerActionPerformed(evt);
            }
        });

        thirtyear_mv_header.setText("Mkt Value");

        fiveyear_risk_header.setText("Risk");

        tenyear_risk_header.setText("Risk");

        thirtyear_risk_header.setText("Risk");

        closing_file_header.setEditable(false);
        closing_file_header.setBackground(new java.awt.Color(204, 204, 255));
        closing_file_header.setText("Closing file");

        twoyear_closing_file_risk.setText(riskbymaturity_seg[0]);

        twoyear_closing_file_mv.setText(riskbymaturity_seg[1]);

        fiveyear_closing_file_risk.setText(riskbymaturity_seg[2]);

        fiveyear_closing_file_mv.setText(riskbymaturity_seg[3]);

        tenyear_closing_file_risk.setText(riskbymaturity_seg[4]);
        tenyear_closing_file_risk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenyear_closing_file_riskActionPerformed(evt);
            }
        });

        tenyear_closing_file_mv.setText(riskbymaturity_seg[5]);
        tenyear_closing_file_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenyear_closing_file_mvActionPerformed(evt);
            }
        });

        thirtyear_closing_file_risk.setText(riskbymaturity_seg[6]);
        thirtyear_closing_file_risk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyear_closing_file_riskActionPerformed(evt);
            }
        });

        thirtyear_closing_file_mv.setText(riskbymaturity_seg[7]);
        thirtyear_closing_file_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyear_closing_file_mvActionPerformed(evt);
            }
        });

        twoyear_hedge_header.setEditable(false);
        twoyear_hedge_header.setBackground(new java.awt.Color(204, 204, 255));
        twoyear_hedge_header.setText("2yr hedge");

        twoyear_hedge_mv.setText(riskbymaturity_seg[8]);

        fiveyear_hedge_mv.setText(riskbymaturity_seg[9]);
        fiveyear_hedge_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveyear_hedge_mvActionPerformed(evt);
            }
        });

        tenyear_hedge_mv.setText(riskbymaturity_seg[10]);

        thirtyear_hedge_mv.setText(riskbymaturity_seg[11]);
        thirtyear_hedge_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyear_hedge_mvActionPerformed(evt);
            }
        });

        yield_curve_header.setEditable(false);
        yield_curve_header.setBackground(new java.awt.Color(204, 204, 255));
        yield_curve_header.setText("Yield Curve");

        twoyear_yield_curve_mv.setText(riskbymaturity_seg[12]);

        fiveyear_yield_curve_mv.setText(riskbymaturity_seg[13]);
        fiveyear_yield_curve_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveyear_yield_curve_mvActionPerformed(evt);
            }
        });

        tenyear_yield_curve_mv.setText(riskbymaturity_seg[14]);

        thirtyear_yield_curve_mv.setText(riskbymaturity_seg[15]);

        button_up.setText("shift 50% up");
        button_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_upMouseClicked(evt);
            }
        });
        button_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_upActionPerformed(evt);
            }
        });

        button_down.setText("shift 50% down");
        button_down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_downMouseClicked(evt);
            }
        });

        button_original.setText("original");
        button_original.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_originalMouseClicked(evt);
            }
        });

        spread_header.setEditable(false);
        spread_header.setBackground(new java.awt.Color(204, 204, 255));
        spread_header.setText("Spread");

        twoyear_spread_mv.setText(spread1);
        twoyear_spread_mv.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                twoyear_spread_mvInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        twoyear_spread_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoyear_spread_mvActionPerformed(evt);
            }
        });

        fiveyear_spread_mv.setText(spread2);
        fiveyear_spread_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveyear_spread_mvActionPerformed(evt);
            }
        });

        tenyear_spread_mv.setText(spread3);
        tenyear_spread_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenyear_spread_mvActionPerformed(evt);
            }
        });

        thirtyear_spread_mv.setText(spread4);
        thirtyear_spread_mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyear_spread_mvActionPerformed(evt);
            }
        });

        execution_time_header2.setEditable(false);
        execution_time_header2.setForeground(new java.awt.Color(255, 51, 51));
        execution_time_header2.setText("execution time:");
        execution_time_header2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execution_time_header2ActionPerformed(evt);
            }
        });

        real_time_header2.setEditable(false);
        real_time_header2.setForeground(new java.awt.Color(255, 0, 0));
        real_time_header2.setText("Real");

        user_time_header2.setEditable(false);
        user_time_header2.setForeground(new java.awt.Color(255, 51, 51));
        user_time_header2.setText("User");

        system_time_header2.setEditable(false);
        system_time_header2.setForeground(new java.awt.Color(255, 51, 51));
        system_time_header2.setText("System");

        sever_side_header2.setEditable(false);
        sever_side_header2.setForeground(new java.awt.Color(255, 51, 51));
        sever_side_header2.setText("(server side)");

        real_time2.setText(riskbymaturity_seg[16]);
        real_time2.setForeground(new java.awt.Color(255, 51, 51));

        user_time2.setText(riskbymaturity_seg[17]);
        user_time2.setForeground(new java.awt.Color(255, 51, 51));

        system_time2.setText(riskbymaturity_seg[18]);
        system_time2.setEditable(false);
        system_time2.setForeground(new java.awt.Color(255, 51, 51));

        jButton1.setBackground(new java.awt.Color(255, 51, 204));
        jButton1.setText("update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel1.setText("                                                                  Risk by Maturity (amounts in 000's)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(507, 507, 507))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(book_header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(twoyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(fiveyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(fiveyear_closing_file_mv)
                                                    .addComponent(fiveyear_mv_header, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                    .addComponent(fiveyear_hedge_mv))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(138, 138, 138)
                                                        .addComponent(tenyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(tenyear_closing_file_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tenyear_closing_file_mv))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(tenyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tenyear_mv_header))))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(fiveyear_spread_mv, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                    .addComponent(fiveyear_yield_curve_mv))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tenyear_yield_curve_mv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tenyear_spread_mv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(twoyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twoyear_mv_header, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(twoyear_closing_file_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fiveyear_closing_file_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fiveyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thirtyear_closing_file_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thirtyear_closing_file_mv)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(thirtyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(thirtyear_yield_curve_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(thirtyear_spread_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(thirtyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(thirtyear_mv_header))
                                .addComponent(thirtyear_header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sever_side_header2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(execution_time_header2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(real_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(user_time2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(real_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(user_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(system_time_header2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(system_time2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twoyear_hedge_header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yield_curve_header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spread_header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(twoyear_yield_curve_mv)
                                    .addComponent(twoyear_hedge_mv)
                                    .addComponent(twoyear_spread_mv, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(closing_file_header, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twoyear_closing_file_risk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_original, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_down)
                    .addComponent(button_up, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirtyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(book_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveyear_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twoyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tenyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tenyear_mv_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoyear_mv_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveyear_mv_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirtyear_risk_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirtyear_mv_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(closing_file_header)
                            .addComponent(twoyear_closing_file_risk)
                            .addComponent(twoyear_closing_file_mv)
                            .addComponent(fiveyear_closing_file_risk)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fiveyear_closing_file_mv)
                                .addComponent(tenyear_closing_file_risk))
                            .addComponent(thirtyear_closing_file_risk)
                            .addComponent(thirtyear_closing_file_mv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twoyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirtyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(twoyear_hedge_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tenyear_hedge_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yield_curve_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(twoyear_yield_curve_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fiveyear_yield_curve_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(thirtyear_yield_curve_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenyear_yield_curve_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(spread_header)
                                .addComponent(twoyear_spread_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fiveyear_spread_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tenyear_spread_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(thirtyear_spread_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(button_up, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_down)
                        .addGap(18, 18, 18)
                        .addComponent(button_original)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(execution_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(real_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(system_time_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sever_side_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(real_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(system_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tenyear_closing_file_mv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenyear_closing_file_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenyear_closing_file_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenyear_closing_file_mvActionPerformed

    private void thirtyear_closing_file_riskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyear_closing_file_riskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirtyear_closing_file_riskActionPerformed

    private void thirtyear_closing_file_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyear_closing_file_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirtyear_closing_file_mvActionPerformed

    private void thirtyear_hedge_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyear_hedge_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirtyear_hedge_mvActionPerformed

    private void fiveyear_yield_curve_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveyear_yield_curve_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveyear_yield_curve_mvActionPerformed

    private void execution_time_header2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execution_time_header2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_execution_time_header2ActionPerformed

    private void fiveyear_hedge_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveyear_hedge_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveyear_hedge_mvActionPerformed

    private void fiveyear_spread_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveyear_spread_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveyear_spread_mvActionPerformed

    private void tenyear_closing_file_riskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenyear_closing_file_riskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenyear_closing_file_riskActionPerformed

    private void button_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_upMouseClicked
        // TODO add your handling code here:
         count *= 1.5;
       
    }//GEN-LAST:event_button_upMouseClicked

    private void twoyear_spread_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoyear_spread_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoyear_spread_mvActionPerformed

    private void twoyear_spread_mvInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_twoyear_spread_mvInputMethodTextChanged
            // TODO add your handling code here:
    }//GEN-LAST:event_twoyear_spread_mvInputMethodTextChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //调用你的连接类  调用获取risk的命令  with count = ?

//        spread1 = "0";
//        spread2 = "0";
//        spread3 = "0";
//        spread4 = "0";
        
        spread1 = twoyear_spread_mv.getText();
        spread2 = fiveyear_spread_mv.getText();
        spread3 = tenyear_spread_mv.getText();
        spread4 = thirtyear_spread_mv.getText();
        
        rate = count -1;
//        
//        String arg1 = "get_risk("+spread1+","+spread2+","+spread3+","+spread4+")";
//        System.out.println(arg1);
//        String arg2 = "get_risk_with_shift("+rate+","+spread1+","+spread2+","+spread3+","+spread4+")";
//       System.out.println(rate);
        this.setVisible(false);
        if (rate == 0){
            
            RiskByMaturityFrame newFrame;
            try {
                newFrame = new RiskByMaturityFrame(socket,spread1,spread2,spread3,spread4,count,rate,1);
                newFrame.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(RiskByMaturityFrame.class.getName()).log(Level.SEVERE, null, ex); 
            }
          }
        else{
            RiskByMaturityFrame newFrame;
            try {
                newFrame = new RiskByMaturityFrame(socket,spread1,spread2,spread3,spread4,count,rate,2);
                newFrame.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(RiskByMaturityFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
       
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void button_downMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_downMouseClicked
        // TODO add your handling code here:
       // count = (int) (count*0.5);
       count *= 0.5;
    }//GEN-LAST:event_button_downMouseClicked

    private void button_originalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_originalMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try { 
            RiskByMaturityFrame newFrame ;
                newFrame = new RiskByMaturityFrame(socket,"0","0","0","0",1,0,1);
                newFrame.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(RiskByMaturityFrame.class.getName()).log(Level.SEVERE, null, ex); 
            }
    }//GEN-LAST:event_button_originalMouseClicked

    private void button_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_upActionPerformed

    private void tenyear_spread_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenyear_spread_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenyear_spread_mvActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void thirtyear_spread_mvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyear_spread_mvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirtyear_spread_mvActionPerformed

    private void tenyear_mv_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenyear_mv_headerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenyear_mv_headerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiskByMaturityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiskByMaturityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiskByMaturityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiskByMaturityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Socket socket = new Socket();
                try {
                    new RiskByMaturityFrame(socket).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RiskByMaturityFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book_header;
    private javax.swing.JButton button_down;
    private javax.swing.JButton button_original;
    private javax.swing.JButton button_up;
    private javax.swing.JTextField closing_file_header;
    private javax.swing.JTextField execution_time_header2;
    private javax.swing.JTextField fiveyear_closing_file_mv;
    private javax.swing.JTextField fiveyear_closing_file_risk;
    private javax.swing.JTextField fiveyear_header;
    private javax.swing.JTextField fiveyear_hedge_mv;
    private javax.swing.JTextField fiveyear_mv_header;
    private javax.swing.JTextField fiveyear_risk_header;
    private javax.swing.JTextField fiveyear_spread_mv;
    private javax.swing.JTextField fiveyear_yield_curve_mv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField real_time2;
    private javax.swing.JTextField real_time_header2;
    private javax.swing.JTextField sever_side_header2;
    private javax.swing.JTextField spread_header;
    private javax.swing.JTextField system_time2;
    private javax.swing.JTextField system_time_header2;
    private javax.swing.JTextField tenyear_closing_file_mv;
    private javax.swing.JTextField tenyear_closing_file_risk;
    private javax.swing.JTextField tenyear_header;
    private javax.swing.JTextField tenyear_hedge_mv;
    private javax.swing.JTextField tenyear_mv_header;
    private javax.swing.JTextField tenyear_risk_header;
    private javax.swing.JTextField tenyear_spread_mv;
    private javax.swing.JTextField tenyear_yield_curve_mv;
    private javax.swing.JTextField thirtyear_closing_file_mv;
    private javax.swing.JTextField thirtyear_closing_file_risk;
    private javax.swing.JTextField thirtyear_header;
    private javax.swing.JTextField thirtyear_hedge_mv;
    private javax.swing.JTextField thirtyear_mv_header;
    private javax.swing.JTextField thirtyear_risk_header;
    private javax.swing.JTextField thirtyear_spread_mv;
    private javax.swing.JTextField thirtyear_yield_curve_mv;
    private javax.swing.JTextField twoyear_closing_file_mv;
    private javax.swing.JTextField twoyear_closing_file_risk;
    private javax.swing.JTextField twoyear_header;
    private javax.swing.JTextField twoyear_hedge_header;
    private javax.swing.JTextField twoyear_hedge_mv;
    private javax.swing.JTextField twoyear_mv_header;
    private javax.swing.JTextField twoyear_risk_header;
    private javax.swing.JTextField twoyear_spread_mv;
    private javax.swing.JTextField twoyear_yield_curve_mv;
    private javax.swing.JTextField user_time2;
    private javax.swing.JTextField user_time_header2;
    private javax.swing.JTextField yield_curve_header;
    // End of variables declaration//GEN-END:variables
}
